version: '2'
services:
    redis:
        image: redis:4-alpine
        ports:
            - "6379:6379"
        volumes:
            - "./docker_data/redis:/data"
        container_name: "GoCoupon_redis_1"
